import type { Metadata } from "next";




export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function NavLayout({ children }: LayoutProps<"/">) {
    return (


        <div>
            <h1 className="text-5xl text-red-500 text-center">Welcome to this section</h1>
            {children}
           
        </div>



    );
}
